"""initial schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("preset", sa.String(length=100), nullable=False),
        sa.Column(
            "extras",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "availability",
        sa.Column("resource", sa.String(length=200), nullable=False),
        sa.Column("day", sa.String(length=200), nullable=False),
        sa.Column("period", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "resource", "day", "period", "status"),
    )
    with op.batch_alter_table("availability", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_availability_dataset_id"), ["dataset_id"], unique=False
        )

    op.create_table(
        "constraint",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("hard", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("constraint", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_constraint_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "day",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("day", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_day_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "event",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=200), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("start_pattern", sa.String(length=200), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=True),
        sa.Column("delivery", sa.String(length=50), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("template", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "event_resource",
        sa.Column("event", sa.String(length=200), nullable=False),
        sa.Column("resource", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "event", "resource"),
    )
    with op.batch_alter_table("event_resource", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_resource_dataset_id"), ["dataset_id"], unique=False
        )

    op.create_table(
        "period",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("start", sa.Time(), nullable=False),
        sa.Column("end", sa.Time(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_break", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("period", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_period_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "pin",
        sa.Column("event", sa.String(length=200), nullable=False),
        sa.Column("day", sa.String(length=200), nullable=True),
        sa.Column("start_period", sa.String(length=200), nullable=True),
        sa.Column(
            "resources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "event", "source"),
    )
    with op.batch_alter_table("pin", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pin_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "reference",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=200), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("reference", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reference_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "reference_type",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "attribute_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("reference_type", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reference_type_dataset_id"), ["dataset_id"], unique=False
        )

    op.create_table(
        "requirement",
        sa.Column("event", sa.String(length=200), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("resource_type", sa.String(length=200), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("filter", sa.Text(), nullable=False),
        sa.Column("capacity_rule", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "event", "ordinal"),
    )
    with op.batch_alter_table("requirement", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_requirement_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "resource",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=200), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent", sa.String(length=200), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resource_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "resource_type",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("exclusive", sa.Boolean(), nullable=False),
        sa.Column("has_capacity", sa.Boolean(), nullable=False),
        sa.Column(
            "attribute_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("resource_type", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_type_dataset_id"), ["dataset_id"], unique=False
        )

    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "progress",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "score_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index("ix_run_status_created", ["status", "created_at"], unique=False)
        batch_op.create_index(
            "uq_run_published",
            ["dataset_id"],
            unique=True,
            postgresql_where=sa.text("published"),
            sqlite_where=sa.text("published"),
        )

    op.create_table(
        "start_pattern",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column(
            "start_periods",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "days",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("start_pattern", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_start_pattern_dataset_id"), ["dataset_id"], unique=False
        )

    op.create_table(
        "template",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=200), nullable=False),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=True),
        sa.Column("targets", sa.Text(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column(
            "fixed",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "pooled",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("start_pattern", sa.String(length=200), nullable=False),
        sa.Column("sessions_per_week", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "code"),
    )
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_template_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "assigned_resource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=200), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "event", "ordinal", "resource"),
    )
    with op.batch_alter_table("assigned_resource", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assigned_resource_run_id"), ["run_id"], unique=False)

    op.create_table(
        "assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=200), nullable=False),
        sa.Column("day", sa.String(length=200), nullable=False),
        sa.Column("start_period", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "event"),
    )
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assignment_run_id"), ["run_id"], unique=False)

    op.create_table(
        "diagnostic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("minimal", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("diagnostic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_diagnostic_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diagnostic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diagnostic_run_id"))

    op.drop_table("diagnostic")
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignment_run_id"))

    op.drop_table("assignment")
    with op.batch_alter_table("assigned_resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assigned_resource_run_id"))

    op.drop_table("assigned_resource")
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_template_dataset_id"))

    op.drop_table("template")
    with op.batch_alter_table("start_pattern", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_start_pattern_dataset_id"))

    op.drop_table("start_pattern")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_run_published",
            postgresql_where=sa.text("published"),
            sqlite_where=sa.text("published"),
        )
        batch_op.drop_index("ix_run_status_created")
        batch_op.drop_index(batch_op.f("ix_run_dataset_id"))

    op.drop_table("run")
    with op.batch_alter_table("resource_type", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_type_dataset_id"))

    op.drop_table("resource_type")
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_dataset_id"))

    op.drop_table("resource")
    with op.batch_alter_table("requirement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_dataset_id"))

    op.drop_table("requirement")
    with op.batch_alter_table("reference_type", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reference_type_dataset_id"))

    op.drop_table("reference_type")
    with op.batch_alter_table("reference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reference_dataset_id"))

    op.drop_table("reference")
    with op.batch_alter_table("pin", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pin_dataset_id"))

    op.drop_table("pin")
    with op.batch_alter_table("period", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_period_dataset_id"))

    op.drop_table("period")
    with op.batch_alter_table("event_resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_resource_dataset_id"))

    op.drop_table("event_resource")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_dataset_id"))

    op.drop_table("event")
    with op.batch_alter_table("day", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_day_dataset_id"))

    op.drop_table("day")
    with op.batch_alter_table("constraint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_constraint_dataset_id"))

    op.drop_table("constraint")
    with op.batch_alter_table("availability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_availability_dataset_id"))

    op.drop_table("availability")
    op.drop_table("dataset")
    # ### end Alembic commands ###
